version: "3"

services:

    postgres:
        image:  postgres:10-alpine
        ports:
            - 5433:5432
        container_name: postgres-database
        restart: always 
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: crud
